# write your docker-compose code here.Use the `docker compose` command instead of the legacy `docker-compose`, as it is integrated into Docker CLI (v20.10+),eliminating the need for a separate binary. It provides better performance, consistency, and is actively maintained, unlike the legacy command.
version: '3.8'
services:
  todo-application:
    image: todo-application-image:latest
    container_name: todo-application-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db-1:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@123
    ports:
      - "8082:8081"
    restart: always
    networks:
      - todo-network
    depends_on:
      - mysql-db
      


  mysql-db:
    image: mysql:latest
    container_name: mysql-db-1
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: tododb
     # MYSQL_USER: root
     # MYSQL_PASSWORD: Root@123
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network


networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data: